version: "3.7"

services:
  api:
    container_name: "api"
    env_file:
      - .env
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    tty: true
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ".:/app"
      - "core_node_modules:/app/node_modules"
    networks:
      - net
    depends_on:
      - db

  db:
    image: "postgres:13.3"
    container_name: "db"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    ports:
      - ${DB_PORT}:5432
    volumes:
      - "db:/var/lib/postgresql/data"

    networks:
      - net

  adminer:
    image: "adminer:4"
    container_name: "db_admin"
    ports:
      - 8090:8080
    networks:
      - net

volumes:
  db:
  core_node_modules:

networks:
  net:
    external: true
